apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "app-updater.fullname" . }}
  labels:
    app:  {{ template "app-updater.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      parallelism: 1
      ttlSecondsAfterFinished: 600
      template:
        spec:
          serviceAccount: {{ template "app-updater.fullname" . }}
          restartPolicy: Never
          containers:
          - image: "quay.io/giantswarm/app-updater:{{ .Values.image.version }}"
            name: {{ template "app-updater.fullname" . }}
            args: ["/opt/script/script.sh"]
            env:
            - name: APP_REPO
              value: {{ .Values.app_repo }}
            - name: APP_NAME
              value: {{ .Values.app_name }}
            volumeMounts:
            - mountPath: /opt/script
              name: {{ template "app-updater.fullname" . }}
              readOnly: false
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "64Mi"
                cpu: "250m"
          volumes:
          - name: {{ template "app-updater.fullname" . }}
            configMap:
              name: {{ template "app-updater.fullname" . }}
