apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "app-updater.fullname" . }}
  labels:
    app:  {{ template "app-updater.fullname" . }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - downwardAPI
  - configMap
