apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "app-updater.fullname" . }}-psp-user
  labels:
    app:  {{ template "app-updater.fullname" . }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "app-updater.fullname" . }}
  verbs:
  - use
- apiGroups:
  - application.giantswarm.io
  resources:
  - apps
  resourceNames:
  - {{ .Values.app_name }}
  verbs:
  - get
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "app-updater.fullname" . }}-psp
  labels:
    app: {{ template "app-updater.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "app-updater.fullname" . }}
  namespace: {{ .Values.clusterID }}
roleRef:
  kind: ClusterRole
  name: {{ template "app-updater.fullname" . }}-psp-user
  apiGroup: rbac.authorization.k8s.io
