apiVersion: v1
appVersion: 0.1.0
description: A Helm chart for app-updater
engine: gotpl
home: https://github.com/giantswarm/app-updater-app
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
name: app-updater-app
version: [[ .Version ]]
